name: CI
on:
  push:
    branches:
      - 'develop'
      - 'master'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00”

jobs:
  test:
    name: (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v2

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Install tcsh and byacc (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install tcsh
          sudo apt-get install byacc

      - name: Install dependencies (Darwin)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install --cask xquartz

      - name: Conda setup
          uses: conda-incubator/setup-miniconda@v2
          with:
            activate-environment: ncl_build
            channels: conda-forge
            channel-priority: strict

      - name: Conda install (Darwin)
        if: matrix.os == 'macos-latest'
        run: |
          conda env update --file .build/envs/Darwin.yml --prune

      - name: Conda install (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          conda env update --file .build/envs/Linux.yml --prune

      - name: Build ncl
        run: |
          conda env list
          bash .build/conda_build.sh

      - name: Run tests
        run: |
          conda env list
          conda activate ncl_build
          conda list
          test "`ncl -V`" = "`cat version`"
          git clone https://github.com/NCAR/ncl_ci_test
          cd ncl_ci_test
          source run_tests.bash
