name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00”

jobs:
  test:
    # if: |
    #   github.repository == 'NCAR/ncl'
    name: Python (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest"]
        python-version: [ "3.6", "3.7", "3.8", "3.9" ]

    steps:
      - uses: actions/checkout@v2
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Create conda environment (Darwin)
        if: matrix.os == 'macos-latest'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        uses: mamba-org/provision-with-micromamba@main
        with:
          micromamba-version: "latest"
          environment-name: ncl_build
          environment-file: .build/envs/Darwin.yml
      - name: Create conda environment (Linux)
        if: matrix.os == 'ubuntu-latest'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        uses: mamba-org/provision-with-micromamba@main
        with:
          micromamba-version: "latest"
          environment-name: ncl_build
          environment-file: .build/envs/Linux.yml
      - name: Build ncl
        shell: sh
        run: |
          source .build/conda_build.sh

      - name: Run tests
        run: |
          test "`ncl -V`" = "`cat version`"
          git clone https://github.com/NCAR/ncl_ci_test
          cd ncl_ci_test
          source run_tests.bash
